openapi: 3.0.2
info:
  description: API for Spintly Identity Management
  version: 1.0.0
  title: Identity Managment
  contact:
    email: admin@mrinq.com
servers:
  - url: 52.66.90.181/idm/v1
    description: Development
paths:
  /v2/identityManagement/oauth/token[token_exchange]:
    post:
      tags:
        - OAuth
      summary: Token generation endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - "urn:ietf:params:oauth:grant-type:token-exchange"
                client_id:
                  type: string
                  format: uuid
                provider:
                  type: string
                  format: uuid
                subject_token_type:
                  type: string
                  enum:
                    - jwt
                subject_token:
                  type: string
                  example: xxxx843234....
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: 2YotnFZFEjr1zCsicMWpAA
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: number
                    example: 3600
                  refresh_token:
                    type: string
                    example: tGzv3JOkF0XG5Qx2TlKWIA
                    


  /v2/identityManagement/oauth/token[username_password]:
    post:
      tags:
        - OAuth
      summary: Token generation endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - "urn:ietf:params:oauth:grant-type:username-password"
                client_id:
                  type: string
                  format: uuid
                username:
                  type: string
                  enum:
                    - jwt
                password:
                  type: string
                  example: xxxx843234....
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: 2YotnFZFEjr1zCsicMWpAA
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: number
                    example: 3600
                  refresh_token:
                    type: string
                    example: tGzv3JOkF0XG5Qx2TlKWIA
                    
  /v2/identityManagement/oauth/token[refresh_token]:
    post:
      tags:
        - OAuth
      summary: Token generation endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - "urn:ietf:params:oauth:grant-type:refresh-token"
          
                refresh_token:
                  type: string
                  example: tGzv3JOkF0XG5Qx2TlKWIA
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: 2YotnFZFEjr1zCsicMWpAA
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: number
                    example: 3600
                  refresh_token:
                    type: string
                    example: tGzv3JOkF0XG5Qx2TlKWIA
  /v2/identityManagement/idps:
    post:
      tags:
        - External IDP Managment
      summary: for creating a new external identity provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - iss
                - aud
                - name
              properties:
                iss:
                  type: string
                aud:
                  type: string
                name:
                  type: string
                subAlias:
                  type: string
                keys:
                  type: array
                  items:
                    type: object
                    properties:
                      keyType:
                        type: string
                      keyVal:
                        type: string

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: object
                    properties:
                      idpId:
                        type: string
                        format: uuid
  "/v2/identityManagement/idps/{idpId}/subjects":
    get:
      parameters:
        - name: idpId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - External IDP Subject Management
      summary: Get list of external idp's subjects
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: array
                    items:
                      type: object
                      properties:
                        sub:
                          type: string
                          format: uuid
                        scopes:
                          type: string
                          example: "acHistory:read acPoint:write"
    post:
      parameters:
        - name: idpId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - External IDP Subject Management
      summary: For creating a new subject under an external IDP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sub
                - scopes
              properties:
                sub:
                  type: string
                scopes:
                  type: string
                identityId:
                  type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: object
  "/v2/identityManagement/identityCredentials":
    post:
      tags:
        - Identity Credentials Management
      summary: For creating a new subject under an external IDP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                identityId:
                  type: integer
                intergratorId:
                  type: integer
                scopes:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: object
  "/v2/identityManagement/idps/{idpId}/subjects/{identityId}":
    delete:
      parameters:
        - name: idpId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: identityId
          in: path
          required: true
          schema:
            type: integer
      tags:
        - External IDP Subject Management
      summary: For deleting an ExternalIdp subject
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: string
                    example: success
  /v2/identityManagement/clients[client_credentials]:
    post:
      tags:
        - Client Management
      summary: For creating a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - grant_type
                - scopes
              properties:
                grantType:
                  type: string
                  example: "urn:ietf:params:oauth:grant-type:client-credentials"
                scopes:
                  type: string
                integratorId:
                  type: integer
                clientName:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: object
                    properties:
                      clientId:
                        type: string
                        example: 5e505642-9024-474d-9434-e5a44f505cc5
                      clientSecret:
                        type: string
                        example: 0d4738a1-8005-4745-a01a-6cf4b9b4034e"

  /v2/identityManagement/clients[token_exchange]:
    post:
      tags:
        - Client Management
      summary: For creating a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - grant_type
                - scopes
              properties:
                grantType:
                  type: string
                  example: urn:ietf:params:oauth:grant-type:token-exchange
                scopes:
                  type: string
                integratorId:
                  type: integer
                  example: 1
                clientName:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: object
                    properties:
                      clientId:
                        type: string
                        example: 5e505642-9024-474d-9434-e5a44f505cc5
  /v2/identityManagement/clients[username_password]:
    post:
      tags:
        - Client Management
      summary: For creating a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - grant_type
                - scopes
              properties:
                grantType:
                  type: string
                  example: urn:ietf:params:oauth:grant-type:username-password
                scopes:
                  type: string
                integratorId:
                  type: integer
                  example: 1
                clientName:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: object
                    properties:
                      clientId:
                        type: string
                        example: 5e505642-9024-474d-9434-e5a44f505cc5

  /v2/identityManagement/identities/{identityId}:
    delete:
      parameters:
        - name: identityId
          in: path
          required: true
          schema:
            type: integer
            format: int
      tags:
        - "Identity"
      summary: To delete the identityId

      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "success"
